# Generated by Django 2.0.4 on 2018-05-02 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('birthday', models.DateField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('established', models.DateField(auto_now_add=True)),
                ('bio', models.CharField(max_length=350)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
