# Generated by Django 2.0.4 on 2018-05-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveltype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solo', models.BooleanField()),
                ('family', models.BooleanField()),
            ],
        ),
    ]
