# Generated by Django 2.0.4 on 2018-05-03 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_traveltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='travelpref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Traveltype'),
            preserve_default=False,
        ),
    ]
