# Generated by Django 2.0.4 on 2018-05-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_travelpref'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveltype',
            name='Friends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveltype',
            name='backpack',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='traveltype',
            name='business',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='traveltype',
            name='couple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveltype',
            name='medical',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='travelpref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Traveltype'),
        ),
        migrations.AlterField(
            model_name='traveltype',
            name='family',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='traveltype',
            name='solo',
            field=models.BooleanField(default=True),
        ),
    ]
