# Generated by Django 2.0.4 on 2018-05-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20180503_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('hotel', models.BooleanField()),
                ('location', models.BooleanField()),
                ('description', models.CharField(max_length=250)),
                ('rate', models.BooleanField()),
                ('established', models.DateField(auto_now_add=True)),
                ('posttraveltype', models.ManyToManyField(related_name='posttraveltype', to='profiles.Traveltype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('suitablefor', models.ManyToManyField(related_name='suitablefor', to='profiles.Traveltype')),
            ],
        ),
    ]
