# Generated by Django 2.0.4 on 2018-05-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20180508_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rate',
            field=models.PositiveIntegerField(),
        ),
    ]
