# Generated by Django 2.0.4 on 2018-05-08 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20180508_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rate',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
