# Generated by Django 2.0.4 on 2018-05-08 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_facility_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facrate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='facrate',
            field=models.ManyToManyField(to='profiles.FacilityRate'),
        ),
    ]
