# Generated by Django 2.0.4 on 2018-05-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20180508_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='facrate',
        ),
        migrations.DeleteModel(
            name='FacilityRate',
        ),
    ]
