# Generated by Django 2.0.4 on 2018-05-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_facilityrating_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityrating',
            name='comment',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
