# Generated by Django 2.0.4 on 2018-05-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_facilityrating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='mx',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
