# Generated by Django 2.0.4 on 2018-05-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_facility_mx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='mx',
        ),
    ]
