# Generated by Django 2.0.4 on 2018-05-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_remove_facility_mx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityrating',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
