# Generated by Django 2.0.4 on 2018-05-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20180512_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityrating',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
